<a href="https://colab.research.google.com/github/KodaliSuchitraKamala/Wipro_Training/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## numpy

 uses:
  1. matrices - coordinates, locations
  2. math functions - stastics / algebra
 functions:
  1. np.random.rand() - uniform random values
  2. np.random.randn() - non-uniform random values
  3. np.dot - multiplication (only on matrices)
  4. np.arange() - random range of values
  5. np.array() - create / delete / access
  6. np.zeros() / ones() - creates an rentire array with 0 / 1
  7. np.mean()
  8. np.std()
  9. np.unique()
  10. np.linalg.inv()
  11. np.eye()


Arrays- import numpy


In [1]:
import numpy as np
x = np.array([1, 2, 3, 4, 5])
print("Array 1-Dimensional ", x)

Array 1-Dimensional  [1 2 3 4 5]


In [2]:
y = np.array([[1, 2], [3, 4]])
print("Array 2-Dimensional\n", y)

Array 2-Dimensional
 [[1 2]
 [3 4]]


In [3]:
o = np.ones((3, 6))
print("Ones \n", o)

Ones 
 [[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]


In [4]:
z = np.zeros((10, 10))
print("Zeros \n", z)

Zeros 
 [[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [5]:
i = np.eye(4)
print("Identical Coordinates:\n", i)

Identical Coordinates:
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [6]:
r = np.arange(0, 11, 2)
print("Array: ", r)

Array:  [ 0  2  4  6  8 10]


In [7]:
seperate = np.linspace(0, 1, 10)
print("Linspace ", seperate)

Linspace  [0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]


In [8]:
seperate = np.linspace(0, 1, 5)
print("Linspace ", seperate)

Linspace  [0.   0.25 0.5  0.75 1.  ]


Operations on arrays using numpy

In [9]:
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])
print("Addition: ", a + b)
print("Product: ", a * b)
print("Square of a: ", a ** 2)
print("Sin values: ", np.sin(a))
print("Mean: ", np.mean(a))
print("Max: ", np.max(a))

Addition:  [ 6  8 10 12]
Product:  [ 5 12 21 32]
Square of a:  [ 1  4  9 16]
Sin values:  [ 0.84147098  0.90929743  0.14112001 -0.7568025 ]
Mean:  2.5
Max:  4


In [10]:
a = np.arange(1, 10)
print(a)
reshaped = a.reshape((3, 3))
print(reshaped)
linear = reshaped.reshape(-1)
print(linear)
linear = reshaped.flatten()
print(linear)
print("Element at (1, 1): ", reshaped[1, 1])
print("Greater than 5: ", linear[linear > 5])
print("Less than 5: ", linear[linear < 5])
print("Random numbers between 0 to 3: ", np.random.rand(3))
print("Random integer:\n", np.random.randint(1, 100, (2, 3)))

[1 2 3 4 5 6 7 8 9]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[1 2 3 4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]
Element at (1, 1):  5
Greater than 5:  [6 7 8 9]
Less than 5:  [1 2 3 4]
Random numbers between 0 to 3:  [0.48012047 0.33926273 0.74707598]
Random integer:
 [[24 31 25]
 [20  6 93]]


code to print a 3x3 matrix which were filled with boolean value True using numpy

In [11]:
import numpy as np
a = np.full((3, 3), True)
print(a)

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


vertical and horizontal - vstack and
hstack

code to take two arrays a and b, integrate a and b vertically and horizontally

In [12]:
import numpy as np
a = list(map(int,input("enter 3 numbers for array a,space separated:").split()))
b = list(map(int,input("enter 3 numbers for array a,space separated:").split()))
a = np.array(a)
b = np.array(b)
v = np.vstack((a,b))
print("vertical stack :\n", np.vstack((a,b)))
print("horizontal stack:\n", np.hstack((a,b)))#also can use concatenate instead hstack
print("element 5 access", v[1][1])

enter 3 numbers for array a,space separated:10 20 30
enter 3 numbers for array a,space separated:40 50 60
vertical stack :
 [[10 20 30]
 [40 50 60]]
horizontal stack:
 [10 20 30 40 50 60]
element 5 access 50


code to extract al the odd numbers from user input and print them in a list using array of numpy

input:1 2 3 4 5 9 8 7 6

output:[1,3,5,9,7]

In [13]:
import numpy as np
data=input("enter numbers seperated by spaces:")
arr=np.array(list(map(int,data.split())))
odd_nums=arr[arr%2==1]
print("odd numbers list:",odd_nums)

enter numbers seperated by spaces:1 2 3 4 5 6 7 8 9
odd numbers list: [1 3 5 7 9]


In [14]:
import numpy as np
data=input("enter numbers seperated by spaces:")
arr=np.array(list(map(int,data.split())),dtype=object)
arr[arr%2==0]='even'
print(arr)

enter numbers seperated by spaces:34 56 34 76 54 43
['even' 'even' 'even' 'even' 'even' 43]


In [15]:
import numpy as np
data=input("enter numbers seperated by spaces:")
arr=np.array(list(map(int,data.split())),dtype=object)
arr[arr%2==1]=True
print(arr)

enter numbers seperated by spaces:34 56 23 76 45
[34 56 True 76 True]


In [16]:
#print even false and odd true
import numpy as np
data=input("enter numbers seperated by spaces:")
arr=np.array(list(map(int,data.split())),dtype=object)
arr[arr%2==0]=False
arr[arr%2==1]=True
print(arr)

enter numbers seperated by spaces:43 65 23 65
[True True True True]


In [17]:
#if multiples of 3 then print true or else false
import numpy as np
data=input("enter numbers seperated by spaces:")
arr=np.array(list(map(int,data.split())))
mask= arr%3 ==0
print(mask)

enter numbers seperated by spaces:34 56 32 54
[False False False  True]


In [18]:
import numpy as np
arr=np.array([[1,2,3], [4,5,6]])
print("element at [0,1]:",arr[0,1])
print("First row:",arr[0, :])
print("first row",arr[:, 1:])
arr[0,0]=100
print("modify:",arr)

element at [0,1]: 2
First row: [1 2 3]
first row [[2 3]
 [5 6]]
modify: [[100   2   3]
 [  4   5   6]]


In [19]:
import numpy as np
arr=np.array([1,2,3,np.nan, 5])
print("Ignoring Nan:",np.nanmean(arr))
print("sum:",np.sum(arr))
#sqrt1.N Ei=1 to N(x~i=u)**2
print("std Ignoring NaN:",np.std(arr[~np.isnan(arr)]))

Ignoring Nan: 2.75
sum: nan
std Ignoring NaN: 1.479019945774904


In [20]:
#replace NaN
import numpy as np
arr=np.array([1,np.nan,3,4,5])
print("replace Nan with 0:",np.where(np.isnan(arr),0,arr))

replace Nan with 0: [1. 0. 3. 4. 5.]


In [21]:
#universal functions unfuncs()
import numpy as np
arr=np.array([1.5,2.9,9.8])
print(arr.astype(np.int32))
arr=np.array([1,2,3,4,5])
print(arr.astype(np.float64))
arr=np.array([1.5,2.9,9.8])
print(arr.astype(str))
arr=np.array([0,1,7,0,-1])
print(arr.astype(bool))
arr=np.array([True,True,False,True])
print(arr.astype(np.int32))
arr=np.array([1.5,2.9,9.8])
print(arr.astype(np.complex128))
arr=np.array([1,2,3,4])
print(arr.astype(np.int8))
arr=np.array([20250802,19990101])
print(arr.astype('datetime64[D]'))
arr=np.array(['123','345'])
print(arr.astype(np.int32))

[1 2 9]
[1. 2. 3. 4. 5.]
['1.5' '2.9' '9.8']
[False  True  True False  True]
[1 1 0 1]
[1.5+0.j 2.9+0.j 9.8+0.j]
[1 2 3 4]
['57414-10-25' '56701-01-15']
[123 345]
